apiVersion: v1
kind: Service
metadata:
  name: random-api
  namespace: random-api
spec:
  selector:
    app: random-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
status:
  loadBalancer:
    ingress:
    - hostname: random-api-xxxxxxxxxxxxxx.elb.us-east-2.amazonaws.com


    